apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksfar
  region: us-east-2
  version: "1.18"
nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    amiFamily: AmazonLinux2
    privateNetworking: true
